networks:
  servers:

services:

  balancer:
    build: .
    command: "balancer"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    environment:
      - CONF_RESPONSE_DELAY_SEC=1
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    environment:
      - CONF_RESPONSE_DELAY_SEC=1
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    environment:
      - CONF_RESPONSE_DELAY_SEC=1
    networks:
      - servers
    ports:
      - "8082:8080"
