name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run Unit Tests
        run: make unit-test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: make build

      - name: Run Integration Tests
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml up -d
          echo "Waiting for test container to finish..."
          docker wait architecture-practice-4-template-test-1 > exit_code.txt
          EXIT_CODE=$(cat exit_code.txt)
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml logs
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml down
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "test failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          fi
